"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

export default function AuthPage() {
  const [mode, setMode] = useState<"signIn" | "signUp">("signIn");
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); try { const supabase = createSupabaseBrowserClient(); const result = mode === "signIn" ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password }); if (result.error) throw result.error; setMessage(mode === "signUp" ? "Check your email to confirm your account, then sign in." : "Signed in. You can return to EzyVest."); } catch (error) { setMessage(error instanceof Error ? error.message : "Authentication is unavailable."); } finally { setBusy(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-[#08090b] px-6 text-white"><section className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[.025] p-8"><Link href="/" className="text-sm font-semibold">EzyVest</Link><p className="mt-7 text-xs tracking-[.2em] text-white/35">YOUR RESEARCH WORKSPACE</p><h1 className="mt-3 text-3xl font-semibold">{mode === "signIn" ? "Welcome back" : "Create your account"}</h1><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none focus:border-white/40" /></label><label className="block text-sm">Password<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none focus:border-white/40" /></label><button disabled={busy} className="w-full rounded-xl bg-white py-3 text-sm font-semibold text-black disabled:opacity-50">{busy ? "Please wait…" : mode === "signIn" ? "Sign in" : "Create account"}</button></form>{message && <p role="status" className="mt-4 text-sm text-white/60">{message}</p>}<button onClick={()=>setMode(mode === "signIn" ? "signUp" : "signIn")} className="mt-6 text-sm text-white/50 underline underline-offset-4">{mode === "signIn" ? "Need an account? Sign up" : "Already have an account? Sign in"}</button></section></main>;
}
