"use client";
import { FormEvent, useState } from "react";
import Navbar from "../components/Navbar";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";
type Result = { answer: string; facts: string[]; analysis: string[]; inferences: string[]; uncertainties: string[]; speculation: string[] };
const sections: (keyof Omit<Result, "answer">)[] = ["facts", "analysis", "inferences", "uncertainties", "speculation"];
export default function ResearchPage() {
  const [question, setQuestion] = useState(""); const [result, setResult] = useState<Result | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); if (question.trim().length < 5) return; setLoading(true); setError(""); try { const response = await fetch("/api/research", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setResult(data); try { const db=createSupabaseBrowserClient(); const {data:{user}}=await db.auth.getUser(); if(user){const session=await db.from("research_sessions").insert({user_id:user.id,title:question.slice(0,120)}).select("id").single(); if(session.data) await db.from("research_messages").insert([{session_id:session.data.id,role:"user",content:{text:question}},{session_id:session.data.id,role:"assistant",content:data}]);}} catch { /* Research remains usable when sign-in or persistence is unavailable. */ } } catch (e) { setError(e instanceof Error ? e.message : "Research is unavailable."); } finally { setLoading(false); } }
  return <main className="min-h-screen bg-[#08090b] text-white"><Navbar /><div className="mx-auto max-w-5xl px-6 py-16"><p className="text-xs tracking-[.2em] text-white/35">EVIDENCE-LED RESEARCH</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">What do you want to understand?</h1><p className="mt-4 max-w-2xl text-white/45">EzyVest separates verified facts, analysis, inference, uncertainty, and speculation—so conclusions stay inspectable.</p><form onSubmit={submit} className="mt-10 rounded-2xl border border-white/10 bg-white/[.03] p-2"><textarea value={question} onChange={e => setQuestion(e.target.value)} placeholder="Ask about a company, event, risk, or financial statement…" className="min-h-32 w-full resize-none bg-transparent p-4 text-base outline-none placeholder:text-white/25" /><div className="flex justify-between border-t border-white/10 px-3 pt-2"><span className="py-2 text-xs text-white/35">No investment recommendations. Source-backed research only.</span><button disabled={loading || question.trim().length < 5} className="rounded-xl bg-white px-5 py-2.5 text-sm font-semibold text-black disabled:opacity-40">{loading ? "Grounding…" : "Research"}</button></div></form>{error && <p className="mt-4 text-sm text-red-300">{error}</p>}{result && <section className="mt-8 space-y-5"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><p className="text-xs tracking-widest text-white/35">ANSWER</p><p className="mt-3 text-lg text-white/80">{result.answer}</p></div><div className="grid gap-4 md:grid-cols-2">{sections.map(key => <div key={key} className="rounded-2xl border border-white/10 p-5"><h2 className="capitalize font-semibold">{key}</h2>{result[key].length ? <ul className="mt-3 space-y-2 text-sm text-white/55">{result[key].map(item => <li key={item}>• {item}</li>)}</ul> : <p className="mt-3 text-sm text-white/35">None available from verified context.</p>}</div>)}</div></section>}</div></main>;
}
