import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { z } from "zod";
import { financialData } from "@/lib/financial-data";
import { createSupabaseServerClient } from "@/lib/supabase/server";

const schema=z.object({symbol:z.string().trim().min(1).max(32),exchange:z.string().trim().min(1).max(100),mic:z.string().trim().min(1).max(20),name:z.string().trim().min(1).max(500),country:z.string().trim().max(8).optional(),currency:z.string().trim().max(8).optional(),type:z.string().trim().max(40).optional()});
async function authenticated(request:NextRequest){const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"");const url=process.env.SUPABASE_URL, key=process.env.SUPABASE_PUBLISHABLE_KEY;if(!token||!url||!key)return false;const auth=createClient(url,key,{global:{headers:{Authorization:`Bearer ${token}`}}});const {data:{user}}=await auth.auth.getUser();return Boolean(user);}
export async function POST(request:NextRequest){try{if(!await authenticated(request))return NextResponse.json({error:"Authentication required."},{status:401});const input=schema.parse(await request.json());const verified=await financialData.search(input.symbol);const match=verified.data?.find(item=>item.symbol.toUpperCase()===input.symbol.toUpperCase()&&item.exchange===input.exchange&&item.mic===input.mic);if(!match)return NextResponse.json({error:"Security could not be verified with the market-data provider."},{status:422});const db=createSupabaseServerClient();if(!db)return NextResponse.json({error:"Server database configuration is unavailable."},{status:503});const exchange=await db.from("exchanges").upsert({name:match.exchange,mic:match.mic,country_code:match.country,currency_code:match.currency},{onConflict:"mic"}).select("id").single();if(exchange.error)throw exchange.error;const existing=await db.from("securities").select("id").eq("exchange_id",exchange.data.id).eq("symbol",match.symbol).eq("security_type",match.type).maybeSingle();if(existing.error)throw existing.error;if(existing.data)return NextResponse.json({securityId:existing.data.id,security:match});const company=await db.from("companies").insert({legal_name:match.name,country_code:match.country}).select("id").single();if(company.error)throw company.error;const security=await db.from("securities").insert({company_id:company.data.id,exchange_id:exchange.data.id,symbol:match.symbol,security_type:match.type,currency_code:match.currency}).select("id").single();if(security.error)throw security.error;return NextResponse.json({securityId:security.data.id,security:match});}catch(error){return NextResponse.json({error:error instanceof z.ZodError?"Invalid security identity.":"Unable to resolve security."},{status:400});}}
